sudo: required
services:
- docker

cache:
  directories:
    - webapp/node_modules
    - webapp/bower_components

install:
  - make binary

script:
  - make test-coverage
  - bash <(curl -s https://codecov.io/bash) -s reports