sudo: required
services:
- docker

cache:
  directories:
    - webapp/node_modules
    - webapp/bower_components

install:
  - make binary

script:
  - make validate test-coverage
  - bash <(curl -s https://codecov.io/bash) -s reports
  - env
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then bash scripts/release; fi'
