language: go

go_import_path: go-dart

go:
  - 1.6

before_install:
  - yes | sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install glide

install:
  - glide install

script:
  - go test -v $(glide novendor)
