sudo: required
services:
- docker

cache:
  directories:
    - webapp/node_modules
    - webapp/bower_components

install:
  - make binary

script:
  - make test
  
after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci
