FROM golang:1.7

RUN apt-get update && \
    apt-get install -y --no-install-recommends unzip && \
    rm -rf /var/lib/apt/lists/*

RUN go get github.com/Masterminds/glide \
 && go get github.com/mjibson/esc \
 && go get github.com/golang/lint/golint

WORKDIR /go/src/github.com/gocaine/go-dart

COPY glide.yaml glide.yaml
COPY glide.lock glide.lock
RUN glide install

COPY . /go/src/github.com/gocaine/go-dart
